QuestionHub/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^questions/',include('questions.urls')),
]

questions/urls.py
from django.conf.urls import url
from . import views
app_name = 'questions'


urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^topic_detail/(?P<pk>[0-9]+)/$',views.TopicDetailView.as_view(),name='topic_detail'),

    #/questions/topic/add/
    url(r'topic/add/$',views.TopicCreate.as_view(),name='topic-add'),
    #/questions/question/add/
    url(r'question/add/$',views.QuestionCreate.as_view(),name='question-add'),

    url(r'question/(?P<pk>[0-9]+)/$',views.QuestionUpdate.as_view(),name='question-update'),

    url(r'question/(?P<pk>[0-9]+)/delete/$',views.QuestionDelete.as_view(),name='question-delete'),

]

questions/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Topic(models.Model):
    topic_name = models.CharField(max_length=300)
    related_to = models.CharField(max_length=300)

    def get_absolute_url(self):
        return reverse('questions:topic_detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.topic_name

class Question(models.Model):
    posted_by = models.CharField(max_length=200)
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    content = models.TextField()

    def get_absolute_url(self):
        return reverse('questions:index')

    def __str__(self):
        return self.content

questions/views.py
from django.shortcuts import render
from . models import Topic,Question
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy

# Create your views here.
# def index(request):
#     all_questions = Question.objects.all()
#     return render(request,'questions/index.html',{'all_questions':all_questions})
#
#
# def detail(request,question_id):
#     ques = Question.objects.get(pk=question_id)
#     return render(request,'questions/detail.html',{'ques':ques})
#Generic views
class IndexView(generic.ListView):
    template_name = 'questions/index.html'
    context_object_name = 'all_questions'

    def get_queryset(self):
        return Question.objects.all()

class TopicDetailView(generic.DetailView):
    model = Topic
    template_name = 'questions/topic_detail.html'

    context_object_name = 'top'

    def get_queryset(self):
        return Topic.objects.all()

class DetailView(generic.DetailView):
    model = Question
    template_name = 'questions/detail.html'

    context_object_name = 'ques'

    def get_queryset(self):
        return Question.objects.all()



class TopicCreate(CreateView):
    model = Topic
    fields = ['topic_name','related_to']



class QuestionCreate(CreateView):
    model = Question
    fields = ['posted_by','topic','content']

class QuestionUpdate(UpdateView):
    model = Question
    fields = ['posted_by','topic','content']


class QuestionDelete(DeleteView):
    model = Question
    fields = ['posted_by','topic','content']
    success_url = reverse_lazy('questions:index')

questions/templates/questions/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}QuestionHub{% endblock %}</title>

    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" >

    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'questions/style.css' %}"/>
  </head>
  <body>

    <nav class="navbar navbar-inverse fixed-top">
      <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'questions:index'  %}">Question Hub</a>
          </div>
          <!--Items-->
          <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active" >
                    <a href="{% url 'questions:index' %}">
                      <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                      Questions

                    </a>
                </li>

                <li class="" >
                    <a href="{% url 'questions:index' %}">
                      <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;
                      Topics

                    </a>
                </li>

              </ul>

              <form class="navbar-form navbar-left" role="search"  method="get" action="#">
                  <div class="form-group">
                      <input type="text" class="form-control" name="q" value="">
                  </div>
                  <button type="submit" class="btn btn-default" >Search</button>
              </form>

              <ul class="nav navbar-nav navbar-right">

                <li class="" >
                    <a href="{% url 'questions:topic-add' %}">
                      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                      Add Topic

                    </a>
                </li>
                <li class="" >
                    <a href="{% url 'questions:question-add' %}">
                      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                      Add Question

                    </a>
                </li>

                <li class="" >
                    <a href="#">
                      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                      Logout

                    </a>
                </li>

              </ul>

          </div>



      </div>

    </nav>
    {% block body %}
    {% endblock %}



  </body>
</html>

questions/templates/questions/detail.html
{% extends 'questions/base.html' %}
{% block title %} Question Details {% endblock %}
{% block body %}
<p>
<h3>Topic is : {{ ques.topic}}</h3>
<h3>Posted by - {{ ques.posted_by }}</h3>
</p>
{% endblock %}

questions/templates/questions/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for=""> {{field.label_tag }}</label>
        <div class="col-sm-10"> {{ field }}

        </div>

    </div>

{%  endfor %}

questions/templates/questions/index.html
{% extends 'questions/base.html' %}
{% block title %}QuestionHub{% endblock %}
{% block body %}
<div class="container">
<div class="jumbotron content">

<p>
<ul>
  {% for question in all_questions %}

      <li><h3><a href="{% url 'questions:detail' question.id%}">{{question.content}}</a></h3> </li>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.


   <a href="{% url 'questions:detail' question.id %}" class = "btn btn-primary btn-sm"> View Details</a>


   <form class="" action="{% url 'questions:question-delete' question.id  %}" method="post" style="display: inline;">
     {% csrf_token %}

     <input type="hidden" name="question_id" value="{{ question.id  }}"/>
     <button type="submit" class="btn btn-default btn-sm" name="button">
       <span class="glyphicon glyphicon-trash"></span>

     </button>

   </form>
  {% endfor%}
</ul>
</p>



</div>
</div>
{% endblock %}


<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" ></script> -->

questions/templates/questions/question_form.html
{% extends 'questions/base.html' %}
{% block title %}Add a new question{% endblock %}
{% block topics_active %} active {% endblock %}


{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                         <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'questions/form-template.html' %}
                              <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success" name="button">Submit</button>

                                </div>

                              </div>


                         </form>

                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

questions/templates/questions/topic_detail.html
{% extends 'questions/base.html' %}
{% block title %} Topic  Details {% endblock %}
{% block body %}
<p>
<h3>Topic is : {{ top.topic_name}}</h3>
<h3>Related to  - {{ top.related_to }}</h3>
</p>
{% endblock %}

questions/templates/questions/topic_form.html
{% extends 'questions/base.html' %}
{% block title %}Add a new Topic{% endblock %}
{% block topics_active %} active {% endblock %}


{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                         <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'questions/form-template.html' %}
                              <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success" name="button">Submit</button>

                                </div>

                              </div>



                         </form>

                    </div>
                </div>

            </div>

        </div>

    </div>



{% endblock %}